[package]
name = "back_to_work"
version = "1.0.0"
edition = "2024"
description = "A small hierarchical task planner"

[dependencies]
eframe = { version = "0.36.2", default-features = false, features = ["default_fonts", "wgpu"] }
rusqlite = { version = "0.38", features = ["bundled"] }

[target.'cfg(target_os = "linux")'.dependencies]
eframe = { version = "0.36.2", default-features = false, features = ["x11", "wayland"] }

[package.metadata.bundle]
name = "Oliver's Aufgabenplaner"
identifier = "com.berningo.back_to_work"
icon = ["assets/icon.icns"]
resources = ["assets"]
category = "public.app-category.utilities"
short_description = "Very simple but effective hierarchical task manager"
